name = "my-django-project"
version = "0.1.0"

# The list of Python dependencies that are needed to build and run the Django backend
[dependencies.python]
python = "3.8.3"
django = "*"

# The list of JavaScript dependencies that are needed to build and run the frontend
[dependencies.javascript]
tailwindcss = "^2.2"

# The build instructions for the project
[build]
script = "python -m pip install -r requirements.txt && npm install"
