name = "auctions"
version = "1.0.0"

# The list of Python dependencies that are needed to build and run the Django backend
[dependencies.python]
asgiref = "3.5.2"
backports.zoneinfo = "0.2.1"
django = "4.1"
gunicorn = "20.1.0"
sqlparse = "0.4.2"
tzdata = "2022.7"
whitenoise = "6.2.0"

# The list of JavaScript dependencies that are needed to build and run the frontend
[dependencies.javascript]
tailwindcss = "^2.2.16"

# The build instructions for the project
[build]
script = "python -m pip install -r requirements.txt && npm install && npm run build"

providers = ['...', 'python']